apiVersion: v1
kind: Pod
metadata:
  name: test-emptydir
  labels:
      type: python-fend
spec:
  containers:
  - image: matei10/hello-mambu-local-storage:0.0.6
    name: python-fend
    volumeMounts:
    - mountPath: /counter
      name: counter-volume
    env:
    - name: COUNTER_PATH
      value: "/counter/main_counter"
  volumes:
  - name: counter-volume
    emptyDir: {}
