apiVersion: v1
kind: Pod
metadata:
  name: test-secret
  labels:
      type: python-fend2
spec:
  containers:
  - image: matei10/hello-mambu-local-storage:0.0.8
    name: python-fend2
    volumeMounts:
    - mountPath: /secrtet1
      name: first-secret
      readOnly: true
    - mountPath: /secrtet2
      name: second-secret
      readOnly: true
  volumes:
  - name: first-secret
    secret:
      secretName: mambu-secret
  - name: second-secret
    secret:
      secretName: mambu-secret2
