apiVersion: v1
kind: Pod
metadata:
  name: configmap-file-pod
  labels:
      type: python-config
spec:
  containers:
    - name: configmap-file-cont
      image: matei10/hello-mambu-local-storage:0.0.11
      volumeMounts:
      - name: config-volume
        mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: file-config
  restartPolicy: Never
