apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-pod
  labels:
      type: python-config-env
spec:
  containers:
    - name: configmap-env-cont
      image: matei10/hello-mambu-local-storage:0.0.11
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: manual-config
              # Specify the key associated with the value
              key: manual.manual_1
